In [1]:
import numpy as np

In [2]:
# 형태변경
na = np.array([[1, 2], [3, 4]])
print(na, id(na))

[[1 2]
 [3 4]] 2088444407280


In [3]:
na1 = na.ravel()
print(na1, id(na1))

[1 2 3 4] 2088445203472


In [4]:
na2 = np.array([1, 2, 3, 4, 5, 6, 7 ,8])
na3 = na2.reshape(4, 2)
print(na2, id(na2))
print(na3, id(na3))

[1 2 3 4 5 6 7 8] 2088444410640
[[1 2]
 [3 4]
 [5 6]
 [7 8]] 2088834428880


In [5]:
print(na3.reshape(-1, 8), na3.reshape(1, -1))

[[1 2 3 4 5 6 7 8]] [[1 2 3 4 5 6 7 8]]


In [6]:
print(na3.reshape(-1, 8))

[[1 2 3 4 5 6 7 8]]


### 인덱싱

In [7]:
a = np.array([1, 2, 3, 4, 5])
a[0]

1

## 윈도우 (<-슬라이싱)

In [8]:
b = a[0:2]   # ndarray에서 슬라이싱하면 윈도우 생성됨!
print(a, b)

b[0] = 10
print(a, b)   # 윈도우 조심!

[1 2 3 4 5] [1 2]
[10  2  3  4  5] [10  2]


## ndarray에서는 슬라이싱할 때 꼬옥 .copy() 붙이기!!!!!!!!

In [9]:
c = a[0:2].copy()
print(a, c)

c[0] = 20
print(a, c)

[10  2  3  4  5] [10  2]
[10  2  3  4  5] [20  2]


In [11]:
# 펜시 인덱싱
# 정수 인덱싱
a = np.array([1, 2, 3, 4, 5])
print(a[0], a[:2], a[::2], a[3::-1])

b = a[[0,2]]   # window가 생성되지 않고 복사
b[0] = 10
print(a, b)

1 [1 2] [1 3 5] [4 3 2 1]
[1 2 3 4 5] [10  3]


In [12]:
# 펜시(논리값) 인덱싱
a = np.array([1, 2, 3, 4, 5])
b = a[[True, False, True, False, True]]

print(b)

[1 3 5]


In [16]:
a > 2  # 요소별 연산
c = a[a > 2]
print(c)

[3 4 5]


In [17]:
# 연산
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = a + b
print(c)

[[ 6  8]
 [10 12]]


In [21]:
print(a.sum())
print(np.sum(a))
print(np.sum(a, axis=0)) # 행방향으로 집합을 만든다.
print(np.sum(a, axis=1)) # 열방향으로 집합을 만든다.
print(a[a > 1].sum())

10
10
[4 6]
[3 7]
9


In [22]:
print(np.any(a >= 4))
print(np.all(a >= 4))

True
False


In [23]:
# 유니버셜함수
a = np.arange(10)
condition = a < 3
np.extract(condition, a)

array([0, 1, 2])

In [24]:
condlist = [a < 3, a > 7]
print(condlist)

[array([ True,  True,  True, False, False, False, False, False, False,
       False]), array([False, False, False, False, False, False, False, False,  True,
        True])]


In [31]:
choicelist = [a, a*2]
print(choicelist)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])]


In [32]:
np.select(condlist, choicelist)

array([ 0,  1,  2,  0,  0,  0,  0,  0, 16, 18])

In [33]:
np.where(a % 2 == 0, '짝수', '홀수')

array(['짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수'],
      dtype='<U2')