In [1]:
import numpy as np

In [3]:
# 형태변경
na = np.array([[1, 2], [3, 4]])
print(na, id(na))

[[1 2]
 [3 4]] 2534983266448


In [4]:
na1 = na.ravel()
print(na1, id(na1))

[1 2 3 4] 2534988217008


In [5]:
na2 = np.array([1, 2, 3, 4, 5, 6, 7 ,8])
na3 = na2.reshape(4, 2)
print(na2, id(na2))
print(na3, id(na3))

[1 2 3 4 5 6 7 8] 2534988216912
[[1 2]
 [3 4]
 [5 6]
 [7 8]] 2534988487568


In [7]:
print(na3.reshape(-1, 8), na3.reshape(1, -1))

[[1 2 3 4 5 6 7 8]] [[1 2 3 4 5 6 7 8]]


In [ ]:
print(na3.reshape(-1, 8))

### 인덱싱

In [8]:
a = np.array([1, 2, 3, 4, 5])
a[0]

1

## 윈도우 (<-슬라이싱)

In [9]:
b = a[0:2]   # ndarray에서 슬라이싱하면 윈도우 생성됨!
print(a, b)

b[0] = 10
print(a, b)   # 윈도우 조심!

[1 2 3 4 5] [1 2]
[10  2  3  4  5] [10  2]


## ndarray에서는 슬라이싱할 때 꼬옥 .copy() 붙이기!!!!!!!!

In [10]:
c = a[0:2].copy()
print(a, c)

c[0] = 20
print(a, c)

[10  2  3  4  5] [10  2]
[10  2  3  4  5] [20  2]
