In [2]:
import numpy as np
# numpy는 CPU만 씀(GPU 무상관)
np.__version__
np.__config__.show()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1991176392224
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:

In [3]:
# 요소별 연산
a = [1, 2, 3]
a*2

[1, 2, 3, 1, 2, 3]

In [5]:
b = [n*2 for n in a]
b

[2, 4, 6]

In [6]:
c = np.array(a) # ndarray(행렬연산, 요소별 연산)
c*2

array([2, 4, 6])

In [18]:
%%time
a = list(range(10000000))

def test():
    for i in range(len(a)):
        a[i] += 1

test()

CPU times: total: 1.44 s
Wall time: 1.5 s


In [24]:
%time a = [n+1 for n in range(10000000)]

CPU times: total: 1.5 s
Wall time: 1.52 s


In [23]:
%%time
b = np.arange(10000000)
c = b+1

CPU times: total: 46.9 ms
Wall time: 45.6 ms


## ndarray
### 생성

In [26]:
data = [0, 1, 2, 3, 4, 5]
nd = np.array(data)
print(nd, type(nd), nd.dtype, nd.shape, nd.size, sep=', ')
print(3 in nd)

[0 1 2 3 4 5], <class 'numpy.ndarray'>, int32, (6,), 6
True


In [28]:
data = [1.2, 1.0, 2.4, 5.4, 3.2]
nd = np.array(data)
print(nd, type(nd), nd.dtype, nd.shape, nd.size, sep=', ')

[1.2 1.  2.4 5.4 3.2], <class 'numpy.ndarray'>, float64, (5,), 5


In [33]:
nd = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(nd, nd.dtype, nd.shape, nd.size, sep=', ')
print(nd.sum(axis=0), nd.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]], int32, (3, 3), 9
[12 15 18] [ 6 15 24]


In [35]:
data = ["가", "나", "다"]
nd = np.array(data)
print(nd, nd.dtype, nd.shape, nd.size, sep=', ')

['가' '나' '다'], <U1, (3,), 3


In [36]:
nd = np.arange(10)
print(nd, nd.dtype, nd.shape, nd.size, sep=', ')

[0 1 2 3 4 5 6 7 8 9], int32, (10,), 10


In [38]:
# 빈 행렬
nd = np.empty(3)
print(nd, nd.dtype, nd.shape, nd.size, sep=', ')

[2.12199579e-314 6.36598737e-314 1.06099790e-313], float64, (3,), 3


In [39]:
# 지정된 값으로 초기화
nd = np.full((2, 3), 3)
print(nd, nd.dtype, nd.shape, nd.size, sep=', ')

[[3 3 3]
 [3 3 3]], int32, (2, 3), 6


In [43]:
# 0으로 초기화
nd = np.zeros((2, 2), dtype=int)
print(nd, nd.dtype, nd.shape, nd.size, sep=', ')

[[0 0]
 [0 0]], int32, (2, 2), 4
